import React, { useState } from 'react';
import { InvestigationReport, DossierDocument } from '../types.js';
import {
  X,
  Printer,
  Copy,
  Check,
  Download,
  FileText,
  ShieldCheck,
} from 'lucide-react';

interface ExportReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  report: InvestigationReport | null;
  documents: DossierDocument[];
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({
  isOpen,
  onClose,
  report,
  documents,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !report) return null;

  const generateMarkdownReport = () => {
    return `# OfferLens Job Offer Reality Check Investigation
**Date:** ${new Date(report.generatedAt).toLocaleDateString()}  
**Target Position:** ${report.candidateRole}  
**Company / Stated Entity:** ${report.companyName}  
**Reality Alignment Score:** ${report.overallAlignmentScore}%  
**Uncertainty Rating:** ${report.uncertaintyRating.toUpperCase()}  

---

## Executive Investigation Summary
> ${report.calibratedVerdictSummary}

*Privacy Audit: ${report.privacySummary.piiTokensMasked} PII tokens locally sanitized before analysis. Zero persistent server retention.*

---

## Key Metrics
- **Contradictions Between Promises & Offer:** ${report.contradictionsCount}
- **Potentially Concerning Signals:** ${report.signalsSummary.highCount + report.signalsSummary.moderateCount}
- **Missing Contractual Protections:** ${report.missingItemsCount}

---

## Cross-Document Contradictions & Divergences
${report.contradictions
  .map(
    (c, i) => `### ${i + 1}. ${c.title} [${c.severity.toUpperCase()} SEVERITY]
- **Category:** ${c.category}
- **Recruiter Promise (${c.claimA.speakerOrChannel}):** "${c.claimA.snippet}"
- **Contract Reality (${c.claimB.speakerOrChannel}):** "${c.claimB.snippet}"
- **Impact Assessment:** ${c.impactAssessment}
- **Uncertainty Context:** ${c.uncertaintyExplanation}
- **Recommended Verification:** ${c.recommendedVerification}
`
  )
  .join('\n')}

---

## Potentially Concerning Signals Detected
${report.signals
  .map(
    (s, i) => `### ${i + 1}. ${s.title} [${s.severity.toUpperCase()}]
- **Calibrated Finding:** ${s.calibratedLanguage}
- **Description:** ${s.description}
- **Evidence Snippet:** "${s.evidence[0]?.snippet || 'Referenced in text'}"
- **Suggested Due Diligence:** ${s.suggestedAction}
`
  )
  .join('\n')}

---

## Missing Information & Blind-Spot Audit
${report.missingInformation
  .map(
    (m, i) => `### ${i + 1}. ${m.topic} [${m.importance.toUpperCase()}]
- **What is Missing:** ${m.whatIsMissing}
- **Why It Matters:** ${m.whyItMatters}
- **Suggested Question:** "${m.suggestedQuestion}"
`
  )
  .join('\n')}

---

## Recommended Recruiter Inquiry Scripts
${report.recruiterQuestions
  .map(
    (q, i) => `### ${i + 1}. ${q.targetDiscrepancyOrIssue}
**Polite Script:**
\`\`\`
${q.scriptPolite}
\`\`\`

**Direct Script:**
\`\`\`
${q.scriptDirect}
\`\`\`

**Firm Script:**
\`\`\`
${q.scriptFirm}
\`\`\`
`
  )
  .join('\n')}

---
*Report generated by OfferLens — Privacy-First Job Offer Reality Checker. The final decision always belongs to the user.*
`;
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdownReport());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const md = generateMarkdownReport();
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `OfferLens_Report_${report.companyName.replace(/[^a-zA-Z0-9]/g, '_')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-fadeIn">
      <div className="bg-slate-900 border border-slate-700/80 rounded-2xl w-full max-w-4xl max-h-[90vh] flex flex-col shadow-2xl text-slate-100 overflow-hidden">
        {/* Header */}
        <div className="p-6 border-b border-slate-800 flex items-center justify-between bg-slate-900/90 no-print">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white">
                Export Job Offer Reality Check Report
              </h3>
              <p className="text-xs text-slate-400">
                Share with a trusted mentor, attorney, or family member
              </p>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handlePrint}
              className="px-3.5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium border border-slate-700 flex items-center gap-1.5 transition"
            >
              <Printer className="w-3.5 h-3.5" />
              Print / Save PDF
            </button>
            <button
              onClick={handleCopyMarkdown}
              className="px-3.5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium border border-slate-700 flex items-center gap-1.5 transition"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? 'Copied' : 'Copy Markdown'}
            </button>
            <button
              onClick={handleDownloadMarkdown}
              className="px-3.5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold shadow transition flex items-center gap-1.5"
            >
              <Download className="w-3.5 h-3.5" />
              Download .md
            </button>
            <button
              onClick={onClose}
              className="p-2 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable & Scrollable Report Preview */}
        <div className="flex-1 p-8 overflow-y-auto bg-slate-950 font-sans text-slate-200 space-y-6">
          <div className="border-b border-slate-800 pb-6 space-y-2">
            <div className="flex items-center justify-between text-xs text-slate-400">
              <span className="font-mono uppercase tracking-wider text-emerald-400 font-bold">
                OfferLens Confidential Investigation
              </span>
              <span>{new Date(report.generatedAt).toLocaleString()}</span>
            </div>
            <h1 className="text-2xl font-black text-white">{report.candidateRole}</h1>
            <p className="text-sm font-semibold text-slate-300">
              Company Entity: {report.companyName}
            </p>
            <div className="inline-flex items-center gap-2 mt-2 px-3 py-1 rounded-full bg-slate-800 border border-slate-700 text-xs font-semibold">
              <span>Reality Alignment Score:</span>
              <span className="text-emerald-400 font-mono font-bold">
                {report.overallAlignmentScore}%
              </span>
              <span>• Uncertainty: {report.uncertaintyRating.toUpperCase()}</span>
            </div>
          </div>

          {/* Finding summary */}
          <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 space-y-2 text-xs leading-relaxed">
            <span className="font-bold text-white block uppercase tracking-wider">
              Calibrated Investigation Finding:
            </span>
            <p className="text-slate-300 font-medium">{report.calibratedVerdictSummary}</p>
          </div>

          {/* Contradictions summary */}
          {report.contradictions.length > 0 && (
            <div className="space-y-3">
              <h3 className="text-sm font-bold text-white uppercase tracking-wider">
                Cross-Document Contradictions ({report.contradictions.length})
              </h3>
              <div className="space-y-3">
                {report.contradictions.map((c, i) => (
                  <div key={i} className="p-4 rounded-xl bg-slate-900 border border-slate-800 text-xs space-y-2">
                    <div className="flex items-center justify-between font-bold text-white">
                      <span>{i + 1}. {c.title}</span>
                      <span className="text-[10px] uppercase font-mono px-2 py-0.5 rounded bg-rose-950 text-rose-300 border border-rose-800">
                        {c.severity}
                      </span>
                    </div>
                    <p className="text-slate-400">{c.summary}</p>
                    <div className="grid grid-cols-2 gap-2 pt-1 font-mono text-[11px]">
                      <div className="p-2 rounded bg-slate-950 border border-amber-900/30 text-amber-200">
                        <strong>Recruiter:</strong> "{c.claimA.snippet}"
                      </div>
                      <div className="p-2 rounded bg-slate-950 border border-rose-900/30 text-rose-200">
                        <strong>Contract:</strong> "{c.claimB.snippet}"
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Signals summary */}
          {report.signals.length > 0 && (
            <div className="space-y-3">
              <h3 className="text-sm font-bold text-white uppercase tracking-wider">
                Potentially Concerning Signals ({report.signals.length})
              </h3>
              <div className="space-y-3">
                {report.signals.map((s, i) => (
                  <div key={i} className="p-4 rounded-xl bg-slate-900 border border-slate-800 text-xs space-y-1.5">
                    <div className="flex items-center justify-between font-bold text-white">
                      <span>{i + 1}. {s.title}</span>
                      <span className="text-[10px] uppercase font-mono px-2 py-0.5 rounded bg-amber-950 text-amber-300 border border-amber-800">
                        {s.severity}
                      </span>
                    </div>
                    <p className="text-slate-300 font-semibold">{s.calibratedLanguage}</p>
                    <p className="text-slate-400">{s.description}</p>
                    <p className="text-[11px] text-emerald-400 pt-1 font-medium">
                      Action: {s.suggestedAction}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Recruiter questions summary */}
          {report.recruiterQuestions.length > 0 && (
            <div className="space-y-3">
              <h3 className="text-sm font-bold text-white uppercase tracking-wider">
                Recommended Recruiter Question Scripts
              </h3>
              <div className="space-y-3">
                {report.recruiterQuestions.slice(0, 3).map((q, i) => (
                  <div key={i} className="p-4 rounded-xl bg-slate-900 border border-slate-800 text-xs space-y-2">
                    <span className="font-bold text-white block">{i + 1}. {q.targetDiscrepancyOrIssue}</span>
                    <div className="p-3 rounded bg-slate-950 border border-slate-800 font-mono text-[11px] text-slate-200 whitespace-pre-wrap">
                      {q.scriptPolite}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="pt-6 border-t border-slate-800 text-center text-[11px] text-slate-500">
            OfferLens is a decision-support tool. It does not provide formal legal advice. The final decision always belongs to the user.
          </div>
        </div>
      </div>
    </div>
  );
};
